using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage;
using TriQL.EntityFrameworkCore.Storage.Internal;
using TriQL.EntityFrameworkCore.Tests.TestUtilities;

namespace TriQL.EntityFrameworkCore.Tests.Storage;

/// <summary>EF2-T2/EF2-T3: Trino literal forms generated by the type mappings, including escaping.</summary>
public sealed class SqlLiteralTests
{
    private static readonly IRelationalTypeMappingSource Source = CreateSource();

    private static IRelationalTypeMappingSource CreateSource()
    {
        using var context = new EmptyContext(new DbContextOptionsBuilder<EmptyContext>().UseTrino("Server=https://x/;User=u").Options);
        return context.GetService<IRelationalTypeMappingSource>();
    }

    private static string Literal<T>(T value, string? storeType = null) =>
        (storeType is null ? Source.FindMapping(typeof(T))! : Source.FindMapping(typeof(T), storeType)!).GenerateSqlLiteral(value);

    public static TheoryData<object, string> ScalarLiterals => new()
    {
        { true, "TRUE" },
        { false, "FALSE" },
        { (sbyte)-128, "TINYINT '-128'" },
        { (byte)255, "SMALLINT '255'" },
        { (short)-32768, "SMALLINT '-32768'" },
        { (ushort)65535, "65535" },
        { -7, "-7" },
        { uint.MaxValue, "BIGINT '4294967295'" },
        { long.MinValue, "BIGINT '-9223372036854775808'" },
        { ulong.MaxValue, "DECIMAL '18446744073709551615'" },
        { 1.5f, "REAL '1.5'" },
        { float.NaN, "REAL 'NaN'" },
        { float.NegativeInfinity, "REAL '-Infinity'" },
        { 0.1d, "DOUBLE '0.1'" },
        { 1e300d, "DOUBLE '1E+300'" },
        { double.PositiveInfinity, "DOUBLE 'Infinity'" },
        { -1.50m, "DECIMAL '-1.50'" },
        { decimal.MaxValue, "DECIMAL '79228162514264337593543950335'" },
        { new DateOnly(1, 1, 1), "DATE '0001-01-01'" },
        { Guid.Parse("0f8fad5b-d9cb-469f-a165-70867728950e"), "UUID '0f8fad5b-d9cb-469f-a165-70867728950e'" },
        { new byte[] { 0x0A, 0x0B, 0xFF }, "X'0A0BFF'" },
        { Array.Empty<byte>(), "X''" },
        { 'x', "'x'" },
        { TimeSpan.FromSeconds(-1.5), "BIGINT '-15000000'" },
    };

    [Theory]
    [MemberData(nameof(ScalarLiterals))]
    public void Scalar_RendersATypedTrinoLiteral(object value, string expected)
    {
        Assert.Equal(expected, Source.FindMapping(value.GetType())!.GenerateSqlLiteral(value));
    }

    [Fact]
    public void IntegerMappings_AcceptAConstantOfAnotherIntegerType()
    {
        // EF generates COALESCE(SUM(x), 0) with an Int32 constant typed by x's bigint mapping.
        Assert.Equal("BIGINT '0'", Source.FindMapping(typeof(long))!.GenerateSqlLiteral(0));
        Assert.Equal("TINYINT '1'", Source.FindMapping(typeof(sbyte))!.GenerateSqlLiteral(1));
        Assert.Equal("DECIMAL '7'", Source.FindMapping(typeof(ulong))!.GenerateSqlLiteral(7));
    }

    [Theory]
    [InlineData("", "''")]
    [InlineData("it's", "'it''s'")]
    [InlineData("''", "''''''")]
    [InlineData("back\\slash", "'back\\slash'")]
    [InlineData("line\nbreak", "'line\nbreak'")]
    [InlineData("😀 ünïcödé", "'😀 ünïcödé'")]
    [InlineData("'; DROP TABLE t; --", "'''; DROP TABLE t; --'")]
    public void String_EscapesQuotesByDoubling_AndNothingElse(string value, string expected)
    {
        Assert.Equal(expected, Literal(value));
        Assert.Equal(expected, Literal(value, "char(40)"));
        Assert.Equal(expected, TrinoSqlGenerationHelper.GenerateStringLiteral(value));
    }

    [Fact]
    public void Timestamp_RendersTheMappingsPrecision_TruncatingFinerTicks()
    {
        var value = new DateTime(2026, 1, 2, 3, 4, 5).AddTicks(1_234_567);

        Assert.Equal("TIMESTAMP '2026-01-02 03:04:05.123456'", Literal(value));
        Assert.Equal("TIMESTAMP '2026-01-02 03:04:05.123'", Literal(value, "timestamp(3)"));
        Assert.Equal("TIMESTAMP '2026-01-02 03:04:05'", Literal(value, "timestamp(0)"));
        Assert.Equal("TIMESTAMP '2026-01-02 03:04:05.1234567'", Literal(value, "timestamp(9)"));
    }

    [Fact]
    public void TimestampWithTimeZone_KeepsTheValuesOffset()
    {
        var value = new DateTimeOffset(2026, 1, 2, 3, 4, 5, TimeSpan.FromHours(2)).AddTicks(1_234_560);

        Assert.Equal("TIMESTAMP '2026-01-02 03:04:05.123456 +02:00'", Literal(value));
        Assert.Equal("TIMESTAMP '2026-01-02 03:04:05.1 +02:00'", Literal(value, "timestamp(1) with time zone"));
        Assert.Equal("TIMESTAMP '2026-01-02 03:04:05.000000 -05:30'", Literal(new DateTimeOffset(2026, 1, 2, 3, 4, 5, TimeSpan.FromMinutes(-330))));
    }

    [Fact]
    public void Time_RendersTheMappingsPrecision()
    {
        var value = new TimeOnly(23, 59, 59).Add(TimeSpan.FromTicks(9_999_999));

        Assert.Equal("TIME '23:59:59.999999'", Literal(value));
        Assert.Equal("TIME '23:59:59'", Literal(value, "time(0)"));
    }
}
