using System.Text;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Update;

namespace TriQL.EntityFrameworkCore.Update.Internal;

/// <summary>
/// Generates the <c>INSERT</c>/<c>UPDATE</c>/<c>DELETE</c> statements of <c>SaveChanges</c>, with
/// <c>"catalog"."schema"."table"</c> names when the model assigns a catalog.
/// </summary>
/// <remarks>
/// <para>
/// Trino answers every DML statement with a one-row result set whose <c>rows</c> column is the number of
/// rows affected. Each command is therefore mapped as a rows-affected-only result set, which EF reads to
/// detect optimistic concurrency conflicts (the role <c>SELECT @@ROWCOUNT</c> or <c>RETURNING 1</c> plays
/// elsewhere). Trino has no <c>RETURNING</c>, so values generated by the database cannot be read back; the
/// model validator rejects them.
/// </para>
/// <para>
/// This is an internal API that supports the EF Core infrastructure and is not subject to the
/// same compatibility standards as public APIs.
/// </para>
/// </remarks>
public class TrinoUpdateSqlGenerator : UpdateSqlGenerator
{
    private const ResultSetMapping RowsAffectedResult = ResultSetMapping.LastInResultSet | ResultSetMapping.ResultSetWithRowsAffectedOnly;

    /// <summary>Initializes a new instance.</summary>
    public TrinoUpdateSqlGenerator(UpdateSqlGeneratorDependencies dependencies)
        : base(dependencies)
    {
    }

    /// <summary>Appends <c>INSERT INTO table (columns) VALUES (values)</c>.</summary>
    public override ResultSetMapping AppendInsertOperation(
        StringBuilder commandStringBuilder,
        IReadOnlyModificationCommand command,
        int commandPosition,
        out bool requiresTransaction)
    {
        ArgumentNullException.ThrowIfNull(commandStringBuilder);
        ArgumentNullException.ThrowIfNull(command);
        EnsureNoReadOperations(command);

        var writeOperations = command.ColumnModifications.Where(o => o.IsWrite).ToList();

        commandStringBuilder.Append("INSERT INTO ").Append(QualifiedTable(command));
        if (writeOperations.Count > 0)
        {
            commandStringBuilder
                .Append(" (")
                .AppendJoin(", ", writeOperations.Select(o => SqlGenerationHelper.DelimitIdentifier(o.ColumnName)))
                .Append(')');
        }

        AppendValuesHeader(commandStringBuilder, writeOperations);
        AppendValues(commandStringBuilder, command.TableName, command.Schema, writeOperations);
        commandStringBuilder.AppendLine(SqlGenerationHelper.StatementTerminator);

        requiresTransaction = false;
        return RowsAffectedResult;
    }

    /// <summary>Appends <c>UPDATE table SET … WHERE key [AND concurrency tokens]</c>.</summary>
    public override ResultSetMapping AppendUpdateOperation(
        StringBuilder commandStringBuilder,
        IReadOnlyModificationCommand command,
        int commandPosition,
        out bool requiresTransaction)
    {
        ArgumentNullException.ThrowIfNull(commandStringBuilder);
        ArgumentNullException.ThrowIfNull(command);
        EnsureNoReadOperations(command);

        var writeOperations = command.ColumnModifications.Where(o => o.IsWrite).ToList();
        if (writeOperations.Any(o => o.JsonPath is not null))
        {
            throw new NotSupportedException("Partial updates of JSON columns are not supported by the Trino EF Core provider.");
        }

        commandStringBuilder
            .Append("UPDATE ")
            .Append(QualifiedTable(command))
            .Append(" SET ")
            .AppendJoin(
                ", ",
                writeOperations.Select(o =>
                {
                    var assignment = new StringBuilder(SqlGenerationHelper.DelimitIdentifier(o.ColumnName)).Append(" = ");
                    AppendUpdateColumnValue(SqlGenerationHelper, o, assignment, command.TableName, command.Schema);
                    return assignment.ToString();
                }));
        AppendWhereClause(commandStringBuilder, command.ColumnModifications.Where(o => o.IsCondition).ToList());
        commandStringBuilder.AppendLine(SqlGenerationHelper.StatementTerminator);

        requiresTransaction = false;
        return RowsAffectedResult;
    }

    /// <summary>Appends <c>DELETE FROM table WHERE key [AND concurrency tokens]</c>.</summary>
    public override ResultSetMapping AppendDeleteOperation(
        StringBuilder commandStringBuilder,
        IReadOnlyModificationCommand command,
        int commandPosition,
        out bool requiresTransaction)
    {
        ArgumentNullException.ThrowIfNull(commandStringBuilder);
        ArgumentNullException.ThrowIfNull(command);
        EnsureNoReadOperations(command);

        commandStringBuilder.Append("DELETE FROM ").Append(QualifiedTable(command));
        AppendWhereClause(commandStringBuilder, command.ColumnModifications.Where(o => o.IsCondition).ToList());
        commandStringBuilder.AppendLine(SqlGenerationHelper.StatementTerminator);

        requiresTransaction = false;
        return RowsAffectedResult;
    }

    /// <summary>The table name, catalog-qualified when the model assigns the table a catalog.</summary>
    private string QualifiedTable(IReadOnlyModificationCommand command)
    {
        var table = SqlGenerationHelper.DelimitIdentifier(command.TableName, command.Schema);
        return command.Table?.GetCatalog() is { } catalog
            ? SqlGenerationHelper.DelimitIdentifier(catalog) + "." + table
            : table;
    }

    // Model validation rejects database-generated values; this guards against any that slip through.
    private static void EnsureNoReadOperations(IReadOnlyModificationCommand command)
    {
        if (command.ColumnModifications.FirstOrDefault(o => o.IsRead) is { } read)
        {
            throw new NotSupportedException(
                $"The column '{read.ColumnName}' of '{command.TableName}' must be read back after saving, which "
                + "Trino cannot do: it has no RETURNING clause. Set the value in .NET instead.");
        }
    }
}
