using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using TriQL.EntityFrameworkCore.Diagnostics.Internal;

namespace TriQL.EntityFrameworkCore.Infrastructure.Internal;

/// <summary>
/// Rejects, when the model is built, what Trino and Iceberg cannot store, each with guidance:
/// values generated by the database (identity, defaults, computed columns, row versions, sequences),
/// a catalog without a schema, entity types sharing a table in different catalogs, and table or column
/// names that differ only by case (Trino stores identifiers in lower case). Warns
/// (<see cref="TrinoEventId.UniqueIndexNotEnforced"/>) about unique indexes and alternate keys, which
/// Trino does not enforce.
/// </summary>
/// <remarks>
/// <para>
/// A value generated on add is accepted when the application or a client-side generator supplies
/// it: a <see cref="Guid"/> (UUIDv7), <see cref="string"/> or <see cref="byte"/>[] key, or any property
/// with <c>HasValueGenerator</c>. A concurrency token is accepted when the application manages it
/// (for example a <c>long Version</c> incremented before <c>SaveChanges</c>).
/// </para>
/// <para>
/// This is an internal API that supports the EF Core infrastructure and is not subject to the
/// same compatibility standards as public APIs.
/// </para>
/// </remarks>
public class TrinoModelValidator : RelationalModelValidator
{
    private static readonly HashSet<Type> ClientGeneratedTypes = [typeof(Guid), typeof(string), typeof(byte[])];

    /// <summary>Initializes a new instance.</summary>
    public TrinoModelValidator(ModelValidatorDependencies dependencies, RelationalModelValidatorDependencies relationalDependencies)
        : base(dependencies, relationalDependencies)
    {
    }

    /// <inheritdoc />
    public override void Validate(IModel model, IDiagnosticsLogger<DbLoggerCategory.Model.Validation> logger)
    {
        ArgumentNullException.ThrowIfNull(model);
        ArgumentNullException.ThrowIfNull(logger);

        base.Validate(model, logger);

        ValidateNoSequences(model);
        foreach (var entityType in model.GetEntityTypes())
        {
            ValidateValueGeneration(entityType);
            ValidateCatalog(entityType);
            ValidateColumnNameCase(entityType);
            WarnAboutUniqueness(entityType, logger);
        }

        ValidateTableNameCase(model);
    }

    /// <summary>Rejects sequences (and so HiLo): Trino has none.</summary>
    protected virtual void ValidateNoSequences(IModel model)
    {
        ArgumentNullException.ThrowIfNull(model);

        if (model.GetSequences().FirstOrDefault() is { } sequence)
        {
            throw new InvalidOperationException(
                $"The model defines the sequence '{sequence.Name}', but Trino has no sequences (so HiLo key generation "
                + "cannot be used either). Generate key values in .NET instead, for example with a Guid key, which the "
                + "Trino provider fills with a UUIDv7.");
        }
    }

    /// <summary>Rejects values the database would have to generate: Trino and Iceberg generate none.</summary>
    protected virtual void ValidateValueGeneration(IEntityType entityType)
    {
        ArgumentNullException.ThrowIfNull(entityType);

        foreach (var property in entityType.GetDeclaredProperties())
        {
            var name = $"'{entityType.DisplayName()}.{property.Name}'";

            if (property.IsConcurrencyToken && property.ValueGenerated == ValueGenerated.OnAddOrUpdate)
            {
                throw new InvalidOperationException(
                    $"The property {name} is a row version (IsRowVersion), which the database would have to update on "
                    + "every write, but Trino has no row versions. Use a concurrency token the application manages "
                    + "instead: for example a 'long Version' property configured with IsConcurrencyToken() and "
                    + "incremented before SaveChanges.");
            }

            if (property.GetComputedColumnSql() is not null)
            {
                throw new InvalidOperationException(
                    $"The property {name} is a computed column (HasComputedColumnSql), but Trino tables have no computed "
                    + "columns. Compute the value in .NET before saving, or in the query that reads it.");
            }

            if (property.FindAnnotation(RelationalAnnotationNames.DefaultValue) is not null || property.GetDefaultValueSql() is not null)
            {
                throw new InvalidOperationException(
                    $"The property {name} has a database default value (HasDefaultValue/HasDefaultValueSql), but Trino "
                    + "tables have no column defaults. Set the default in .NET instead, for example with a property "
                    + "initializer.");
            }

            if (property.ValueGenerated.HasFlag(ValueGenerated.OnUpdate))
            {
                throw new InvalidOperationException(
                    $"The property {name} is configured to be generated by the database on update "
                    + $"({property.ValueGenerated}), but Trino generates no values. Set it in .NET before saving and "
                    + "configure it with ValueGeneratedNever().");
            }

            if (property.ValueGenerated == ValueGenerated.OnAdd
                && property.GetValueGeneratorFactory() is null
                && !ClientGeneratedTypes.Contains(Nullable.GetUnderlyingType(property.ClrType) ?? property.ClrType))
            {
                throw new InvalidOperationException(
                    $"The property {name} is configured to be generated by the database on add (ValueGeneratedOnAdd), "
                    + "but Trino has no identity columns or sequences. Set the value in .NET and configure the property "
                    + "with ValueGeneratedNever(), use a Guid key (the Trino provider generates a UUIDv7), or supply a "
                    + "client-side generator with HasValueGenerator.");
            }
        }

        // An owned collection's key by convention includes a shadow ordinal the application cannot set.
        if (entityType.FindOwnership() is { IsUnique: false } && entityType.FindPrimaryKey() is { } key
            && key.Properties.FirstOrDefault(p => p.IsShadowProperty() && !p.IsForeignKey()
                && p.ValueGenerated == ValueGenerated.Never && p.GetValueGeneratorFactory() is null) is { } ordinal)
        {
            throw new InvalidOperationException(
                $"The owned collection '{entityType.DisplayName()}' (OwnsMany) has the key part '{ordinal.Name}', which "
                + "the database would have to generate, but Trino generates no values. Give the owned type a key the "
                + "application sets: for example a Guid 'Id' property configured with HasKey(\"Id\") inside OwnsMany, "
                + "which the Trino provider fills with a UUIDv7.");
        }
    }

    /// <summary>Rejects a catalog without a schema: Trino needs <c>catalog.schema.table</c>.</summary>
    protected virtual void ValidateCatalog(IEntityType entityType)
    {
        ArgumentNullException.ThrowIfNull(entityType);

        if (entityType.GetCatalog() is not { } catalog)
        {
            return;
        }

        var tableName = entityType.GetTableName() ?? entityType.GetViewName();
        var schema = entityType.GetTableName() is not null ? entityType.GetSchema() : entityType.GetViewSchema();
        if (tableName is not null && schema is null)
        {
            throw new InvalidOperationException(
                $"The entity type '{entityType.DisplayName()}' is mapped to '{tableName}' in the catalog '{catalog}' but has "
                + "no schema. Trino needs both to name a table in another catalog: set one with ToTable(name, schema) "
                + "or with HasDefaultSchema.");
        }
    }

    /// <summary>Rejects two columns of one table whose names differ only by case.</summary>
    protected virtual void ValidateColumnNameCase(IEntityType entityType)
    {
        ArgumentNullException.ThrowIfNull(entityType);

        if (entityType.GetTableName() is not { } tableName)
        {
            return;
        }

        var table = StoreObjectIdentifier.Table(tableName, entityType.GetSchema());
        var columns = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var property in entityType.GetProperties())
        {
            if (property.GetColumnName(table) is not { } column)
            {
                continue;
            }

            if (columns.TryGetValue(column, out var existing) && existing != column)
            {
                throw new InvalidOperationException(
                    $"The columns '{existing}' and '{column}' of table '{table.DisplayName()}' (entity type "
                    + $"'{entityType.DisplayName()}') differ only by case. Trino identifiers are case-insensitive and stored "
                    + "in lower case, so they would name the same column. Rename one with HasColumnName.");
            }

            columns[column] = column;
        }
    }

    /// <summary>
    /// Rejects two tables or views whose names differ only by case, and entity types mapped to the same
    /// table in different catalogs.
    /// </summary>
    protected virtual void ValidateTableNameCase(IModel model)
    {
        ArgumentNullException.ThrowIfNull(model);

        var tables = new Dictionary<string, (string Name, IEntityType EntityType)>(StringComparer.OrdinalIgnoreCase);
        foreach (var entityType in model.GetEntityTypes())
        {
            var (name, schema) = entityType.GetTableName() is { } tableName
                ? (tableName, entityType.GetSchema())
                : (entityType.GetViewName(), entityType.GetViewSchema());
            if (name is null)
            {
                continue;
            }

            var catalog = entityType.GetCatalog();
            var qualified = string.Join(".", new[] { schema, name }.Where(p => p is not null));
            if (tables.TryGetValue(qualified, out var existing))
            {
                if (existing.Name != qualified)
                {
                    throw new InvalidOperationException(
                        $"The tables '{existing.Name}' (entity type '{existing.EntityType.DisplayName()}') and '{qualified}' "
                        + $"(entity type '{entityType.DisplayName()}') differ only by case. Trino identifiers are "
                        + "case-insensitive and stored in lower case, so they would name the same table. Rename one with ToTable.");
                }

                if (existing.EntityType.GetCatalog() != catalog)
                {
                    throw new InvalidOperationException(
                        $"The entity types '{existing.EntityType.DisplayName()}' and '{entityType.DisplayName()}' are both "
                        + $"mapped to '{qualified}', in the catalogs '{existing.EntityType.GetCatalog()}' and '{catalog}'. EF "
                        + "identifies a table by its schema and name only, so it would treat them as one table. Entity types "
                        + "that share a table must be in the same catalog; tables in different catalogs need different "
                        + "schema-qualified names.");
                }

                continue;
            }

            tables[qualified] = (qualified, entityType);
        }
    }

    /// <summary>Warns about unique indexes and alternate keys, which Trino does not enforce.</summary>
    protected virtual void WarnAboutUniqueness(IEntityType entityType, IDiagnosticsLogger<DbLoggerCategory.Model.Validation> logger)
    {
        ArgumentNullException.ThrowIfNull(entityType);
        ArgumentNullException.ThrowIfNull(logger);

        foreach (var index in entityType.GetDeclaredIndexes().Where(i => i.IsUnique))
        {
            logger.UniqueIndexNotEnforced($"unique index {Format(index.Properties)}", entityType.DisplayName());
        }

        foreach (var key in entityType.GetDeclaredKeys().Where(k => !k.IsPrimaryKey()))
        {
            logger.UniqueIndexNotEnforced($"alternate key {Format(key.Properties)}", entityType.DisplayName());
        }
    }

    private static string Format(IReadOnlyList<IProperty> properties) =>
        "{" + string.Join(", ", properties.Select(p => $"'{p.Name}'")) + "}";
}
