using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore.Query;
using Microsoft.EntityFrameworkCore.Query.SqlExpressions;

namespace TriQL.EntityFrameworkCore.Query.Internal;

/// <summary>
/// Generates Trino SQL from EF's relational query tree. Differences from EF's default SQL:
/// <c>OFFSET m</c> before <c>LIMIT n</c> for paging, <c>||</c> for string concatenation (Trino's
/// <c>+</c> is arithmetic only), and <c>LATERAL</c> joins in place of <c>CROSS APPLY</c>/<c>OUTER APPLY</c>.
/// </summary>
/// <remarks>
/// This is an internal API that supports the EF Core infrastructure and is not subject to the
/// same compatibility standards as public APIs.
/// </remarks>
public class TrinoQuerySqlGenerator : QuerySqlGenerator
{
    /// <summary>Initializes a new instance.</summary>
    public TrinoQuerySqlGenerator(QuerySqlGeneratorDependencies dependencies)
        : base(dependencies)
    {
    }

    /// <summary>Does nothing: Trino has no <c>TOP</c>; row limits are generated by <see cref="GenerateLimitOffset"/>.</summary>
    protected override void GenerateTop(SelectExpression selectExpression)
    {
    }

    /// <summary>
    /// Generates <c>OFFSET m</c>, <c>LIMIT n</c> or both — in that order, which Trino requires.
    /// Both accept parameters, so paged queries keep a cacheable SQL text.
    /// </summary>
    protected override void GenerateLimitOffset(SelectExpression selectExpression)
    {
        ArgumentNullException.ThrowIfNull(selectExpression);

        if (selectExpression.Offset is { } offset)
        {
            Sql.AppendLine().Append("OFFSET ");
            Visit(offset);
        }

        if (selectExpression.Limit is { } limit)
        {
            Sql.AppendLine().Append("LIMIT ");
            Visit(limit);
        }
    }

    /// <summary>Uses <c>||</c> for string concatenation: Trino's <c>+</c> does not apply to <c>varchar</c>.</summary>
    protected override string GetOperator(SqlBinaryExpression binaryExpression)
    {
        ArgumentNullException.ThrowIfNull(binaryExpression);

        return binaryExpression.OperatorType == ExpressionType.Add && binaryExpression.Type == typeof(string)
            ? " || "
            : base.GetOperator(binaryExpression);
    }

    /// <summary>The scale <c>AVG</c> over a decimal is computed at, unless the argument's own scale is larger.</summary>
    internal const int DecimalAverageScale = 10;

    /// <summary>
    /// Widens the argument of <c>AVG</c> over a decimal to <c>decimal(38, s)</c>, with
    /// <c>s = max(10, argument scale)</c>. Trino's <c>avg(decimal(p,s))</c> returns <c>decimal(p,s)</c>,
    /// rounding the average to the column's scale (the average of 4.50 and 1.25 would be 2.88), while
    /// .NET's <c>Average</c> keeps the fraction.
    /// </summary>
    protected override Expression VisitSqlFunction(SqlFunctionExpression sqlFunctionExpression)
    {
        ArgumentNullException.ThrowIfNull(sqlFunctionExpression);

        if (sqlFunctionExpression is not { IsBuiltIn: true, Name: "AVG", Arguments: [var argument] }
            || (Nullable.GetUnderlyingType(argument.Type) ?? argument.Type) != typeof(decimal))
        {
            return base.VisitSqlFunction(sqlFunctionExpression);
        }

        var (operand, distinct) = argument is DistinctExpression d ? (d.Operand, true) : (argument, false);
        var scale = Math.Max(DecimalAverageScale, operand.TypeMapping?.Scale ?? 0);

        Sql.Append("AVG(");
        if (distinct)
        {
            Sql.Append("DISTINCT ");
        }

        Sql.Append("CAST(");
        Visit(operand);
        Sql.Append(string.Create(System.Globalization.CultureInfo.InvariantCulture, $" AS decimal(38, {scale})))"));
        return sqlFunctionExpression;
    }

    /// <summary>Generates the provider's own SQL expressions.</summary>
    protected override Expression VisitExtension(Expression extensionExpression)
    {
        ArgumentNullException.ThrowIfNull(extensionExpression);

        if (extensionExpression is not TrinoStringAggregateExpression aggregate)
        {
            return base.VisitExtension(extensionExpression);
        }

        Sql.Append("array_join(array_agg(");
        Visit(aggregate.Value);
        if (aggregate.Orderings.Count > 0)
        {
            Sql.Append(" ORDER BY ");
            for (var i = 0; i < aggregate.Orderings.Count; i++)
            {
                if (i > 0)
                {
                    Sql.Append(", ");
                }

                Visit(aggregate.Orderings[i]);
            }
        }

        Sql.Append("), ");
        Visit(aggregate.Separator);
        Sql.Append(")");
        return aggregate;
    }

    /// <summary>Generates <c>CROSS APPLY</c> as <c>CROSS JOIN LATERAL</c>.</summary>
    protected override Expression VisitCrossApply(CrossApplyExpression crossApplyExpression)
    {
        ArgumentNullException.ThrowIfNull(crossApplyExpression);

        Sql.Append("CROSS JOIN LATERAL ");
        Visit(crossApplyExpression.Table);
        return crossApplyExpression;
    }

    /// <summary>Generates <c>OUTER APPLY</c> as <c>LEFT JOIN LATERAL … ON TRUE</c>.</summary>
    protected override Expression VisitOuterApply(OuterApplyExpression outerApplyExpression)
    {
        ArgumentNullException.ThrowIfNull(outerApplyExpression);

        Sql.Append("LEFT JOIN LATERAL ");
        Visit(outerApplyExpression.Table);
        Sql.Append(" ON TRUE");
        return outerApplyExpression;
    }
}
