using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Conventions;
using Microsoft.EntityFrameworkCore.Metadata.Conventions.Infrastructure;

namespace TriQL.EntityFrameworkCore.Metadata.Conventions;

/// <summary>
/// Keys are generated by the database only where a client can generate them instead. Trino and Iceberg
/// have no identity columns or sequences, so an integer key is not <see cref="ValueGenerated.OnAdd"/> by
/// convention (the application sets it); a <see cref="Guid"/> key stays <see cref="ValueGenerated.OnAdd"/>,
/// and the provider generates a version 7 (time-ordered) UUID for it on the client.
/// </summary>
/// <remarks>
/// Default values and computed columns keep the value generation EF gives them, so that the model
/// validator can reject them with guidance rather than have them silently ignored.
/// </remarks>
public class TrinoValueGenerationConvention : RelationalValueGenerationConvention
{
    /// <summary>Initializes a new instance.</summary>
    public TrinoValueGenerationConvention(
        ProviderConventionSetBuilderDependencies dependencies,
        RelationalConventionSetBuilderDependencies relationalDependencies)
        : base(dependencies, relationalDependencies)
    {
    }

    /// <inheritdoc />
    protected override ValueGenerated? GetValueGenerated(IConventionProperty property)
    {
        ArgumentNullException.ThrowIfNull(property);

        var valueGenerated = base.GetValueGenerated(property);
        if (valueGenerated == ValueGenerated.OnAdd
            && (Nullable.GetUnderlyingType(property.ClrType) ?? property.ClrType) != typeof(Guid)
            && property.FindAnnotation(RelationalAnnotationNames.DefaultValue) is null
            && property.GetDefaultValueSql() is null
            && property.GetComputedColumnSql() is null)
        {
            return null;
        }

        return valueGenerated;
    }
}
